### ISSUE TITLE
need proper GNU v3 compat license.

### ISSUE THREAD

**Issue by milkypostman** [webframp/sicp-info#6]
https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

**Comment by webframp** [comment]
Thanks or bringing this to my attention. I have no problem doing this and I fully support GPL licensing but it's still a gray area for me and the usual IANL disclaimers apply.

This was just repackaging of the texinfo files for my personal benefit so that I could easily install and workthrough SICP exercises directly in emacs. I went ahead and added to melpa in case anyone else wanted it too, not really sure how useful it is to others.

Here's my dilema: The original content of the book is licensed by MIT under the creative commons license indicated here: https://mitpress.mit.edu/sicp/full-text/book/book-Z-H-2.html

- [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/)

This license allows the current usage I think which falls under:

> remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.

but I don't think it would allow me to re-license:

> You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.

Since according to the CC link _"Version 4.0 of CC's Attribution-ShareAlike (BY-SA) license is one-way compatible with the GNU General Public License version 3.0 (GPLv3)."_ and this is not _technically_ software, what would you prefer I do? 

The CC license is already indicated in the pseudo-library file: https://github.com/webframp/sicp-info/blob/master/sicp.el#L12

I'm happy to make any adjustments I can to be compatible with the standards you're applying to the project but relicensing this content under a strict GPLv3 doesn't seem like something I'm allowed to do.

**Comment by purcell** [comment]
I feel like there would be no problem with the (mostly-empty) .el file here being clearly licenced as GPLv3, while the "info" content included in the package would be licenced under different terms. The point of the licence alignment work we've been doing is to ensure that any elisp we're distributing is licenced compatibly with Emacs. Do you agree, @milkypostman?

**Comment by milkypostman** [comment]
it's unclear how these licenses work together.

my understanding as "not a copyright lawyer", is that elisp must adhere to
GPLv3 because it is a plugin (https://www.gnu.org/licenses/
gpl-faq.html#GPLPlugins). to me info files do not seem to fit into this
same definition.

**Comment by webframp** [comment]
Ok @milkypostman @purcell what do you think of the changes in #7?

**Comment by purcell** [comment]
Looks good to me.
